### ISSUE TITLE
Generic caching for steps

### ISSUE THREAD

**Issue by joshuataylor** [wojtekmach/req#112]
Hi!

I'm writing `req_snowflake`, and like `req_bigquery` I am in need of storing the token. But this would be slightly different and cached at a request level (so when a different user/password/role/etc is passed in, it returns a different token).

Maybe there could be a recommended way of caching, I like the way `req_bigquery` does it, maybe something along those lines?

**Comment by wojtekmach** [comment]
Hey, thanks for looking into req_bigquery and req_snowflake!

I'm not sure token caching is very Req specific, I'd say the only particular thing is this: it is very important that we fetch from the cache in a _request step_, so that we always have a fresh token when we make requests. But broadly speaking I'd say you'd want something like [Goth](https://github.com/peburrows/goth): a GenServer that maintains an ets table, you always fetch the token from ets in the caller process, you prefetch the token on server boot, and you periodically fetch new token (a few minutes before it is about to expire).

Does that help at all?

**Comment by joshuataylor** [comment]
It does, is having it per plugin okay? I don't think many would req plugins require caching intnhis manner, mostly plugins involving authentication to third parties where a login step is required.

Snowflake works like this:

1/ Login using their login endpoint with either Username/Password, Key Pair or OAuth. You are then returned a token and how long it is valid for.

2/ This token can then be used in subsequent steps.

If you then do another step, it should use the cached token, or fallback to reauthing.

Should that GenServer be in the req_snowflake module? Otherwise we could use ets or whatever to store it. This is also per user/password, but IMHO most systems won't have many different users. So won't be a huge amount of memory used.

**Comment by wojtekmach** [comment]
Yes, I think per plugin is OK. As we add more plugins we can consider extracting and consolidating things but let's not do it too prematurely.

ets is definitely the way to go. The only question is if you want to have one process per user/pass pair, or just one process that maintains multiple pairs. I believe it might be easier to implement the former actually, you just need to start them under dynamic supervisor.

**Comment by joshuataylor** [comment]
Perfect, thanks!
