### ISSUE TITLE
update/2 duplicate headers

### ISSUE THREAD

**Issue by ckoch-cars** [wojtekmach/req#165]
BLUF:
It's possible to duplicate headers, including the authorization header, using the update/2 function. 

Req version: 0.3.4

I'm not 100% sure if this is a bug or the "correct" behaviour.
Under previous versions of req, we were using the `merge_options/2` function to, well, merge options.
With the deprecation to the use of `:headers` in that function and the change to `update/2`, it's possible to duplicate the headers, including the "authorization" header. This can cause some authenticated requests to fail. 

Per the [RFC 9110 5.3 Field Order](https://www.rfc-editor.org/rfc/rfc9110.html#name-field-order): 

> This means that, aside from the well-known exception noted below, a sender MUST NOT generate multiple field lines with the same name in a message (whether in the headers or trailers) or append a field line when a field line of the same name already exists in the message, unless that field's definition allows multiple field line values to be recombined as a comma-separated list (i.e., at least one alternative of the field's definition allows a comma-separated list, such as an ABNF rule of #(values) defined in [Section 5.6.1](https://www.rfc-editor.org/rfc/rfc9110.html#abnf.extension)).

Example (iex)
```
mix.install [:req]
req = Req.new(headers: [{"authorization", "12345"}])  
=> 
  %Req.Request{
  ...
  headers: [{"authorization", "12345"}],
  ...
  }

Req.update(req, headers: [{"authorization", "23456"}])
=> 
  %Req.Request{
  ...
  headers: [{"authorization", "12345"}, {"authorization", "23456"}],
  ...
  }
```

**Comment by wojtekmach** [comment]
Yeah that's definitely unexpected, thank you for the report.

**Comment by wojtekmach** [comment]
OK, so to give some more context, `Req.Request.merge_options` accidentally allowed :url, :headers, etc, it never did anything with them, it just stored them under `req.options` but no step would ever pick them up from there. I deprecated passing these to merge_options but I should have been clearer that they never did something. So yeah, Req.update is _not_ a direct replacement because it _does_.

Some more context. From day 1, Req merged headers:

```elixir
iex> Req.new(headers: [a: 1]) |> Req.get!(url: "https://httpbin.org/headers", headers: [a: 2]) |> then(& &1.body["headers"]["A"])
"1,2"
```

So Req.update isn't different. I need to do a lot more research to figure out if we should keep this behaviour or we should break it.

For authentication there shouldn't be a need to set it via headers, that's why auth/1 step and the :auth option exists for.

I just realised a new version where we can set the raw value of the header:

```elixir
Req.get!("https://httpbin.org/headers", auth: "hi").body["headers"]["Authorization"]
#=> "hi"
```

and sure enough:

```elixir
Req.new(auth: "hi", url: "https://httpbin.org/headers")
|> Req.update(auth: "hey")
|> Req.get!(auth: "hello")
|> then(& &1.body["headers"]["Authorization"])
#=> "hello"
```

**Comment by ckoch-cars** [comment]
@wojtekmach that's a great point about using the `auth` function.

**Comment by wojtekmach** [comment]
This was totally a nasty bug, thanks again for reporting it @ckoch-cars and apologies for the delay!
