### ISSUE TITLE
Headers downcase warning

### ISSUE THREAD

**Issue by rlopzc** [wojtekmach/req#240]
I've migrated to Req 0.4.1, and I've been getting a lot of warnings about headers needing to be downcased.

I use req as a proxy to another HTTP backend, and the logs are becoming huge by `req`.

Req already downcases the headers [here](https://github.com/wojtekmach/req/blob/187b9a450211ef3f87d3ecca43f1c3d1bb118902/lib/req.ex#L1127).

Do you know how I can disable the warning?

I don't see a reason to downcase the headers of each request if Req is already handling it internally.

**Comment by wojtekmach** [comment]
Thank you for feedback. I just released v0.4.2 which removes the warning.

We emitted the warning because there are two ways to access headers:

1. `Req.Response.get_header(resp, "content-type")`
2. `response.headers["content-type"]`

in the former case we can ensure the given header name is treated as case-insensitive. in the latter we can't, it is what it is.

so the idea was to "teach" people to always use downcase header names. but yeah, this model breaks for use cases like yours. I have updated the docs to mention we're automatically downcasing and hopefully that will be enough for folks not to shoot themselves into the foot.
