### ISSUE TITLE
Add a way to build Req struct with all steps available but disabled

### ISSUE THREAD

**Issue by wojtekmach** [wojtekmach/req#263]
One idea is to explicitly put default options:

```elixir
iex> Req.new().options
%{retry: :safe_transient, ...}
```

and add a function that adds built-in steps, e.g. Req.Steps.attach/1.

Putting this together we'd have:

```elixir
iex> r = Req.Request.new() |> Req.Steps.attach()
iex> Req.get!(r, url: "https://reqbin.org/json").body
"[{\"y\":2,\"x\":1},{\"y\":4,\"x\":3}]"
iex> Req.get!(r, url: "https://reqbin.org/json", decode_body: true).body
[%{"x" => 1, "y" => 2}, %{"x" => 3, "y" => 4}]
```

**Comment by thbar** [comment]
A word of feedback on that: I have found that in my cases, a lot of default steps make sense (e.g. retry, redirect...) while other do not. In particular I often need to "just download as it is on the remote server", so ideally I would want a compressed transfer, but that the payload remains exactly as it is on the other side, and also not decode it. Currently my solution for this is `[compressed: false, decode_body: false]`. 

I do not have a clear answer even just as a user, but at least this is a bit of feedback :smile: to mull over.

**Comment by wojtekmach** [comment]
For that particular case, `raw: true` is the way to go. If you're downloading things and keep around as files, `into: File.stream!("foo")` is another one.

**Comment by thbar** [comment]
> For that particular case, raw: true is the way to go.

Oooh, thanks, somehow I missed this!

> If you're downloading things and keep around as files, into: File.stream!("foo") is another one.

Here is exactly what we are currently doing (for streaming):

https://github.com/etalab/transport-site/pull/3585/files#diff-428ec48076375768e9f08394a290384c7e4df31d03f554c336169535dc12ca32R260

Somehow based on my tests I think we _had_ to pass `[compressed: false, decode_body: false]`, but I guess I'll have to double check, I may have been confused here (since I started non-streaming in initial prototypes!).

**Comment by wojtekmach** [comment]
Let's stick to `Req.Request.new()` and users manually setting up everything for now.
