### ISSUE TITLE
How to implement max_body_length?

### ISSUE THREAD

**Issue by bitboxer** [wojtekmach/req#355]
I want to limit the amount of data our users can download. With `HTTPoison` I could use the `max_body_length` option for this. Does req has something similar?

**Comment by wojtekmach** [comment]
There is nothing built-in at the moment. If Finch does it, https://github.com/sneako/finch/pull/182, we will expose this in Req too. In the meantime, you can do it manually, something like:

```elixir
req =
  Req.new(
    into: fn {:data, data}, {req, resp} ->
      req = update_in(req.private.resp_body_size, & &1 + byte_size(data))
  
      if req.private.resp_body_size < 10_000 do
        {:cont, {req, resp}}
      else
        {:halt, {req, RuntimeError.exception("body too big")}}
      end
    end
  end)
  |> Req.Request.put_private(:resp_body_size, 0)
```

(Of course you can make max resp body size configurable via option, package this into a step, etc.)

Since it's being tracked in Finch I'll close this for now.
