### ISSUE TITLE
Support passing netrc data without needing a real file

### ISSUE THREAD

**Issue by ewildgoose** [wojtekmach/req#425]
I have a server that I need to fetch files from. On first fetch it will demand authentication and redirect me to a site on a different domain, which accepts basic auth to login. That gives me a cookie that I can save and re-present to the original site.

I can handle all the redirects myself and add my own auth headers after verifying I'm being redirected to the correct second domain, however, it seems as though I could leverage the auto redirect feature here. Firstly I'm not totally sure that the existing netrc code picks the redirected domain to use for it's credentials (and not the original URL) - note I only checked the code, didn't try it empirically? Secondly I don't want to have to create a real netrc file to implement this, so the feature request is:

- Can we either have the auth calls accept domain names, or can we have a way to pass the netrc data directly, perhaps as a map?

I think this is a relatively important feature if we are using redirects. I see there is some security feature to avoid presenting auth if the base url changes, but it might be the best solution to have the auth specifically tied to a domain?

Thanks for considering this

**Comment by wojtekmach** [comment]
I'm thinking about removing .netrc support for Req v1.0 actually (move it to a req_netrc package) since there are some security considerations I'd rather not deal with, users storing plain text passwords etc, hence making it opt-in. So I'm not planning to work on this here. That being said, it seems you want to pass credentials per hostname in a programatic way, not necessarily in the netrc format right? For that I'd add a custom step:

```elixir
req =
  Req.new()
  |> Req.Request.prepend_request_steps(:my_step, fn
    req when req.url.host == "host1" ->
      Req.merge(req, auth: {:bearer, "token1"})
    req when req.url.host == "host2" ->
      Req.merge(req, auth: {:bearer, "token2"})
    req ->
      req
  end)
```

I'm going to close this as I don't have plans to extend netrc further but please feel free to continue discussing this. WDYT about this solution?
