### ISSUE TITLE
`Req.Test` fails to handle plug result if `into: :self`

### ISSUE THREAD

**Issue by mruoss** [wojtekmach/req#440]
I try to run the following code:

```ex
Req.Test.stub(:foo, fn conn -> Req.Test.text(conn, "okay") end)
Req.get!(base_url: "http://www.example.com", into: :self, plug: {Req.Test, :foo})
```

This raises the following exception:

```
** (Protocol.UndefinedError) protocol Collectable not implemented for :self of type Atom. This protocol is implemented for the following type(s): BitString, File.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Mix.Shell, Req.Utils.CollectWithHash
    (elixir 1.17.2) lib/collectable.ex:1: Collectable.impl_for!/1
    (elixir 1.17.2) lib/collectable.ex:92: Collectable.into/1
    (req 0.5.8) lib/req/steps.ex:1046: Req.Steps.handle_plug_result/2
    (req 0.5.8) lib/req/request.ex:1106: Req.Request.run_request/1
    (req 0.5.8) lib/req/request.ex:1050: Req.Request.run/1
    (req 0.5.8) lib/req.ex:1106: Req.request!/2
    #cell:pxciqv2ibo257vwc:3: (file)
```

Looking at the case stmt in [`lib/req/steps.ex:1001`](https://github.com/wojtekmach/req/blob/v0.5.7/lib/req/steps.ex#L1001C1-L1002C1), `:self` is really missing. Was this done on purpose?

**Comment by wojtekmach** [comment]
Thank you for the record, fixed on main. Note due to limitations of Plug.Test even if response have multiple chunks (e.g. calling Plug.Conn.chunk/2 multiple times), we'd receive just one `{:data, body}` message with the entire response body. I hope to maybe improve that aspect in the future (https://github.com/elixir-plug/plug/pull/1160).

**Comment by mruoss** [comment]
This is good enough for me. Thanks for the quick fix!
